/*Queries that provide answers to the questions from all projects.*/
SELECT * FROM animals WHERE name LIKE '%mon';
SELECT name FROM animals WHERE date_of_birth  BETWEEN '2016-01-01' AND '2019-12-31'; 
SELECT name FROM animals WHERE neutured = true AND escapet_attempts < 3;
SELECT date_of_birth FROM animals WHERE name = 'Agumon' OR NAME = 'Pikachu';
SELECT name,escapet_attempts FROM animals WHERE weight_kg > 10.5;
SELECT * FROM animals WHERE neutured = true;
SELECT * FROM animals WHERE name!= 'Gabumon';
SELECT * FROM animals WHERE weight_kg >= 10.4 AND weight_kg <= 17.3;
BEGIN;
UPDATE animals SET species = 'unspecified';
ROLLBACK;
BEGIN;
UPDATE animals SET species = 'digimon' WHERE name LIKE '%mon';
UPDATE animals SET species = 'pokemon' WHERE species is  null;
COMMIT;
BEGIN;
DELETE FROM animals;
ROLLBACK;
BEGIN;
DELETE FROM animals WHERE date_of_birth > '2022-jan-1';
SAVEPOINT current_data;
UPDATE animals SET weight_kg =(weight_kg  * -1);
ROLLBACK TO SAVEPOINT current_data;
UPDATE animals SET weight_kg =(weight_kg  * -1) WHERE weight_kg < 0;
COMMIT;
SELECT COUNT(id) AS totalAnimals FROM animals;
SELECT COUNT(id) FROM animals WHERE escapet_attempts = 0;
SELECT SUM(weight_kg) / COUNT(id) FROM animals;
SELECT id,escapet_attempts, name FROM animals WHERE escapet_attempts = (SELECT MAX(escapet_attempts) FROM animals);
SELECT id,escapet_attempts, name FROM animals WHERE escapet_attempts = (SELECT MAX(escapet_attempts) FROM animals);
 SELECT MIN (weight_kg), MAX (weight_kg) FROM animals;
 SELECT AVG(escapet_attempts) FROM animals WHERE date_of_birth BETWEEN '1990-01-1' AND '2000-12-31';
 UPDATE animals SET species_id =2 WHERE name LIKE '%mon';
UPDATE animals SET species_id = 1 WHERE species_id IS NULL;
UPDATE animals SET owner_id = (SELECT id FROM owners WHERE full_name = 'Sam Smith') WHERE name = 'Agumon';
UPDATE animals SET owner_id= (SELECT id FROM owners WHERE full_name = 'Jennifer Orwell') WHERE name IN ('Gabumon','Pikachu');UPDATE animals SET owner_id = (SELECT id FROM owners WHERE full_name = 'Bob') WHERE name IN ('Devimon','Plantmon');
UPDATE animals SET owner_id = (SELECT id FROM owners WHERE full_name = 'Melody Pond') WHERE name IN ('Blossom','Squirtle','Charmander');
UPDATE animals SET owner_id = (SELECT id FROM owners WHERE full_name = 'Dean Winchester') WHERE name IN ('Angemon','Boarmon');
SELECT name FROM animals INNER JOIN owners ON animals.owner_id = owners.id WHERE owners.full_name = 'Melody Pond';
select species.name, count(animals.id) from animals INNER JOIN species ON animals.species_id = species.id group by species.id;
select owners.full_name AS owner,animals.name AS animalName, species.name AS Type FROM animals INNER JOIN owners ON  animals.owner_id = owners.id INNER JOIN species ON animals.species_id = species.id WHERE species.name = 'Digimon' AND owners.full_name = 'Jennifer Orwell';
SELECT owners.full_name, animals.name, escapet_attempts FROM animals INNER JOIN owners ON animals.owner_id = owners.id WHERE escapet_attempts = 0 AND owners.full_name = 'Dean Winchester'
SELECT owners.full_name FROM owners INNER JOIN animals ON owners.id = animals.owner_id GROUP BY owners.full_name ORDER BY COUNT(*) DESC LIMIT 1;
